name: Robeats
description: A music player that syncs over a local network.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^2.0.6
  rxdart: ^0.21.0
  dart_tags: ^0.1.1
  audioplayers: ^0.10.1
  path_provider: ^0.5.0+1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
  - assets/compact-disc-image-transparent.png
  uses-material-design: true